using Xunit.Runner.InProc.SystemConsole;

namespace Composa.App.Tests;

internal static class TestProgram
{
    public static int Main(string[] args)
    {
        // xUnit 3.2.2's Run installs a shutdown watchdog even for -assemblyInfo.
        // On a slow Windows process exit it writes a status line after the JSON,
        // breaking VSTest discovery: https://github.com/xunit/xunit/issues/3576.
        // EntryPoint performs the same metadata query without that watchdog.
        // Remove this workaround when Avalonia's adapter supports xUnit 4.
        if (args.Length == 1 && string.Equals(args[0], "-assemblyInfo", StringComparison.OrdinalIgnoreCase))
        {
            using var runner = new ConsoleRunner(args);
            return runner.EntryPoint().GetAwaiter().GetResult();
        }

        // Preserve xUnit's generated dispatch, including MTP and normal test shutdown checks.
        return AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
    }
}
